---
openapi: 3.0.2
info:
  title: Company
  version: 0.0.1
  description: API definition of company
  contact:
    name: creator's name
    url: 'http://creator.homepage.address'
    email: creator@creator.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
paths:
  /companies:
    summary: Global operations on companies
    get:
      tags:
        - companies
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
              examples:
                companies_json:
                  value:
                    - id: 1
                      name: A string
                      industry: A string
                      foundedDate: value
          description: Get list of companies
      operationId: GetCompany
      summary: Get list of companies
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
            examples:
              '1':
                value:
                  id: 1
                  name: A string
                  industry: A string
                  foundedDate: value
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
              examples:
                '1':
                  value:
                    id: 1
                    name: A string
                    industry: A string
                    foundedDate: value
          description: Changed Company
      operationId: Post Company
      summary: Post Company
  '/companies/{id}':
    summary: Specific operation on companies
    get:
      parameters:
        - examples:
            '1':
              value: 1
          name: id
          description: Company name
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
              examples:
                '1':
                  value:
                    id: 1
                    name: A string
                    industry: A string
                    foundedDate: value
          description: companies with specified id
      operationId: GetCompanyById
      summary: Get Company by id
      description: Get Company by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
            examples:
              '1':
                value:
                  id: 1
                  name: A string
                  industry: A string
                  foundedDate: value
        required: true
      parameters:
        - examples:
            '1':
              value: 1
          name: id
          description: Company name
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
              examples:
                '1':
                  value:
                    id: 1
                    name: A string
                    industry: A string
                    foundedDate: value
          description: Changed Company
      operationId: PatchCompany
      summary: Patch existing Company
    parameters:
      - name: id
        description: Company id
        schema:
          type: integer
        in: path
        required: true
components:
  schemas:
    Company:
      title: Root Type for Company
      description: The root of the Company type's schema.
      type: object
      properties:
        id:
          description: id of this Company
          type: integer
        name:
          description: name of this Company
          type: string
        industry:
          description: industry of this Company
          type: string
        foundedDate:
          description: foundedDate of this Company
          type: string
tags:
  - name: Company
    description: Company resource
